const localApiPort = new URLSearchParams(location.search).get('apiPort') || '8791';
export const API = /^(?:localhost|127\.0\.0\.1)$/.test(location.hostname) ? `http://127.0.0.1:${localApiPort}` : 'https://radarfico-api.automacaofico.workers.dev';
// Static assets must resolve from site root. Relative paths break inside
// /operacao, /sala and /historico.
export const AXIS_URL = '/assets/data/fico-axis-full.json';
export const RISK = { low:{label:'Baixo',color:'#2f8f68'},moderate:{label:'Moderado',color:'#e0b02f'},high:{label:'Alto',color:'#ed7b28'},critical:{label:'Crítico',color:'#d63c32'} };
export const STATUS = { scheduled:'Programada',active:'Em andamento',paused:'Pausada',awaiting_definition:'Aguardando definição',closed:'Encerrada',cancelled:'Cancelada',not_located:'Não localizada',stopped:'Paralisada pela FICO' };
export const PACKAGES=[{id:'P01',start:0,end:38100,color:'#0075a9'},{id:'P02',start:38100,end:71300,color:'#55a646'},{id:'P03',start:71300,end:104500,color:'#ee7623'},{id:'P04',start:104500,end:131260,color:'#7b61a8'},{id:'P05',start:131260,end:167300,color:'#008a8a'},{id:'P06',start:167300,end:225000,color:'#c34f5d'},{id:'P07',start:225000,end:239950,color:'#657583'},{id:'P08',start:239950,end:292260,color:'#b27a19'}];
export const $=(id)=>document.getElementById(id);
export function localDate(value=new Date()){
  const d=new Date(value);
  return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
}
export async function loadAxis(){
  const response=await fetch(AXIS_URL);
  if(!response.ok)throw new Error('Não foi possível carregar eixo ferroviário.');
  const data=await response.json();
  if(!Array.isArray(data.points)||!data.points.length)throw new Error('Eixo ferroviário indisponível.');
  return data.points;
}
export function formatKm(value){const n=Math.max(0,Math.round(Number(value)||0));return `${Math.floor(n/1000)}+${String(n%1000).padStart(3,'0')}`;}
export function parseKm(value){const s=String(value).trim().replace(',','.');if(/^\d+\+\d{1,3}$/.test(s)){const [k,m]=s.split('+');return Number(k)*1000+Number(m);}const n=Number(s);return Number.isFinite(n)?(n<1000?n*1000:n):null;}
export function fmtDate(value){return value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';}
export function packageAt(km){return PACKAGES.find(x=>km>=x.start&&km<x.end)||PACKAGES.at(-1);}
export async function api(path,options={}){const token=sessionStorage.getItem('ficoRadarToken');const headers={...(options.headers||{}),...(token?{authorization:`Bearer ${token}`}:{})};if(options.body)headers['content-type']='application/json';const response=await fetch(`${API}${path}`,{...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Falha de comunicação com o Radar FICO.');error.status=response.status;throw error;}return data;}
export function mapStyle(){return{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap'},satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:17,attribution:'Esri'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.65,'raster-contrast':.08,'raster-brightness-max':.93}},{id:'satellite',type:'raster',source:'satellite',layout:{visibility:'none'}}]};}
export function axisTools(axis){
  function pointAt(target){if(!axis.length)return null;if(target<=axis[0].station_m)return axis[0].coordinate;if(target>=axis.at(-1).station_m)return axis.at(-1).coordinate;let lo=0,hi=axis.length-1;while(lo+1<hi){const mid=Math.floor((lo+hi)/2);if(axis[mid].station_m<=target)lo=mid;else hi=mid;}const a=axis[lo],b=axis[hi],r=(target-a.station_m)/Math.max(1,b.station_m-a.station_m);return[a.coordinate[0]+(b.coordinate[0]-a.coordinate[0])*r,a.coordinate[1]+(b.coordinate[1]-a.coordinate[1])*r];}
  function slice(start,end){const out=[pointAt(start)];axis.forEach(p=>{if(p.station_m>start&&p.station_m<end)out.push(p.coordinate);});out.push(pointAt(end));return out.filter(Boolean);}
  function project(lng,lat){let best=null;for(let i=1;i<axis.length;i++){const a=axis[i-1],b=axis[i],x=lng,y=lat,dx=b.coordinate[0]-a.coordinate[0],dy=b.coordinate[1]-a.coordinate[1],t=Math.max(0,Math.min(1,((x-a.coordinate[0])*dx+(y-a.coordinate[1])*dy)/(dx*dx+dy*dy||1))),px=a.coordinate[0]+dx*t,py=a.coordinate[1]+dy*t,scale=111320*Math.cos(lat*Math.PI/180),dist=Math.hypot((lng-px)*scale,(lat-py)*111320);if(!best||dist<best.distanceM)best={stationM:a.station_m+(b.station_m-a.station_m)*t,distanceM:dist,coordinate:[px,py]};}return best;}
  return{pointAt,slice,project};
}
export function addRadarLayers(map,axis,fronts,ldls=[],circulations=[],activePackage='all'){
  const t=axisTools(axis),railData={type:'Feature',properties:{name:'Linha tronco FICO'},geometry:{type:'LineString',coordinates:axis.map(p=>p.coordinate)}};
  if(map.getSource('radar-rail-axis'))map.getSource('radar-rail-axis').setData(railData);else{map.addSource('radar-rail-axis',{type:'geojson',data:railData});map.addLayer({id:'radar-rail-shadow',type:'line',source:'radar-rail-axis',paint:{'line-color':'#fff','line-width':12,'line-opacity':.94}});map.addLayer({id:'radar-rail-line',type:'line',source:'radar-rail-axis',paint:{'line-color':'#073554','line-width':8,'line-opacity':1}});}
  const packageData={type:'FeatureCollection',features:PACKAGES.map(p=>({type:'Feature',properties:{id:p.id,color:p.color,active:activePackage===p.id},geometry:{type:'LineString',coordinates:t.slice(p.start,p.end)}}))};
  if(map.getSource('radar-packages'))map.getSource('radar-packages').setData(packageData);else{map.addSource('radar-packages',{type:'geojson',data:packageData});map.addLayer({id:'radar-packages',type:'line',source:'radar-packages',paint:{'line-color':['get','color'],'line-width':4.5,'line-opacity':.82}});map.addLayer({id:'radar-package-active-halo',type:'line',source:'radar-packages',filter:['==',['get','active'],true],paint:{'line-color':'#fff','line-width':12,'line-opacity':.96}});map.addLayer({id:'radar-package-active',type:'line',source:'radar-packages',filter:['==',['get','active'],true],paint:{'line-color':['get','color'],'line-width':7,'line-opacity':1}});}
  const features=[],pointFeatures=[];fronts.forEach((front)=>front.segments.forEach((s,i)=>{const props={id:front.id,segment:i,risk:front.risk_level,status:front.effectiveStatus,color:RISK[front.risk_level]?.color||'#667'};if(Math.abs(Number(s.kmEnd)-Number(s.kmStart))<10)pointFeatures.push({type:'Feature',properties:props,geometry:{type:'Point',coordinates:t.pointAt(Number(s.kmStart))}});else features.push({type:'Feature',properties:props,geometry:{type:'LineString',coordinates:t.slice(s.kmStart,s.kmEnd)}});}));const data={type:'FeatureCollection',features};if(map.getSource('fronts'))map.getSource('fronts').setData(data);else{map.addSource('fronts',{type:'geojson',data});map.addLayer({id:'fronts-shadow',type:'line',source:'fronts',paint:{'line-color':'#fff','line-width':15,'line-opacity':.96}});map.addLayer({id:'fronts-lines',type:'line',source:'fronts',paint:{'line-color':['get','color'],'line-width':9,'line-opacity':['case',['in',['get','status'],['literal',['closed','cancelled']]],.45,1],'line-dasharray':['case',['in',['get','status'],['literal',['paused','awaiting_definition','stopped']]],['literal',[1.2,1.2]],['literal',[1,0]]]}});}
  const pointData={type:'FeatureCollection',features:pointFeatures};if(map.getSource('front-points'))map.getSource('front-points').setData(pointData);else{map.addSource('front-points',{type:'geojson',data:pointData});map.addLayer({id:'front-points-halo',type:'circle',source:'front-points',paint:{'circle-radius':11,'circle-color':'#fff','circle-opacity':.96,'circle-stroke-width':2,'circle-stroke-color':'#073554'}});map.addLayer({id:'front-points',type:'circle',source:'front-points',paint:{'circle-radius':6,'circle-color':['get','color'],'circle-stroke-width':2,'circle-stroke-color':'#fff'}});}
  const ldlFeatures=ldls.flatMap(x=>(x.lines||['line01']).map(()=>({type:'Feature',properties:{id:x.id,code:x.permanent_code},geometry:{type:'LineString',coordinates:t.slice(Number(x.km_start),Number(x.km_end))}})));const ldlData={type:'FeatureCollection',features:ldlFeatures};if(map.getSource('radar-ldls'))map.getSource('radar-ldls').setData(ldlData);else{map.addSource('radar-ldls',{type:'geojson',data:ldlData});map.addLayer({id:'radar-ldls',type:'line',source:'radar-ldls',paint:{'line-color':'#9d1d1d','line-width':3,'line-dasharray':[2,2],'line-opacity':.8}});}
  const circulationData={type:'FeatureCollection',features:circulations.map(x=>({type:'Feature',properties:{id:x.id,code:x.permanent_code},geometry:{type:'LineString',coordinates:t.slice(Number(x.km_start),Number(x.km_end))}}))};if(map.getSource('radar-circulations'))map.getSource('radar-circulations').setData(circulationData);else{map.addSource('radar-circulations',{type:'geojson',data:circulationData});map.addLayer({id:'radar-circulations',type:'line',source:'radar-circulations',paint:{'line-color':'#7350a8','line-width':4,'line-dasharray':[1,1.5],'line-opacity':.9}});}
  return t;
}
export function installMapLegend(map,showCco=true){
  const frame=map.getContainer().closest('.map-frame');if(!frame||frame.querySelector('.map-layer-key'))return;
  const key=document.createElement('aside');key.className='map-layer-key';key.setAttribute('aria-label','Legenda e camadas do mapa');
  key.innerHTML=`<strong>LEITURA DO MAPA</strong><p><i class="key-line packages"></i>Pacotes P01–P08</p><p><i class="key-line work"></i>Faixa ou ponto = frente · cor = risco</p><p><i class="key-line dashed"></i>Tracejado = aguardando, pausada ou paralisada</p>${showCco?'<p><i class="key-line ldl"></i>LDL ativa <i class="key-line circulation"></i>Movimentação CCO</p>':''}<div class="map-layer-toggles"><button type="button" aria-pressed="true" data-layers="radar-packages,radar-package-active-halo,radar-package-active">PACOTES</button><button type="button" aria-pressed="true" data-layers="fronts-shadow,fronts-lines,front-points-halo,front-points">FRENTES</button>${showCco?'<button type="button" aria-pressed="true" data-layers="radar-ldls,radar-circulations">CCO</button>':''}</div>`;
  key.querySelectorAll('[data-layers]').forEach(button=>button.addEventListener('click',()=>{const visible=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(visible));button.classList.toggle('is-off',!visible);button.dataset.layers.split(',').forEach(id=>{if(map.getLayer(id))map.setLayoutProperty(id,'visibility',visible?'visible':'none');});}));
  frame.append(key);
}
export function installWeatherModule(map){
  const frame=map.getContainer().closest('.map-frame'),toolbar=frame?.querySelector('.map-toolbar');if(!frame||!toolbar||toolbar.querySelector('[data-weather]'))return;
  const button=document.createElement('button');button.type='button';button.dataset.weather='';button.className='secondary';button.textContent='PREVISÃO DE CHUVA';button.setAttribute('aria-pressed','false');toolbar.append(button);
  const panel=document.createElement('section');panel.className='weather-panel';panel.hidden=true;panel.setAttribute('aria-label','Previsão de chuva de hoje');frame.append(panel);
  let forecast=null,index=0;
  const makeData=()=>{const features=(forecast?.points||[]).flatMap(point=>{const mm=Number(point.precipitation?.[index]||0);return mm<.1?[]:[{type:'Feature',properties:{mm},geometry:{type:'Point',coordinates:[Number(point.longitude),Number(point.latitude)]}}];});return{type:'FeatureCollection',features};};
  const paint=()=>{const data=makeData();if(map.getSource('weather-forecast'))map.getSource('weather-forecast').setData(data);else{map.addSource('weather-forecast',{type:'geojson',data});map.addLayer({id:'weather-forecast',type:'heatmap',source:'weather-forecast',paint:{'heatmap-weight':['interpolate',['linear'],['get','mm'],.1,.08,2,.65,8,1],'heatmap-intensity':1,'heatmap-color':['interpolate',['linear'],['heatmap-density'],0,'rgba(140,236,243,0)',.18,'#8cecf3',.48,'#2898ed',.78,'#1664d8',1,'#35a84a'],'heatmap-radius':58,'heatmap-opacity':.58}},'radar-rail-shadow');}const time=forecast.times[index]?.slice(11,16)||'AGORA';panel.querySelector('output').textContent=time;panel.querySelector('input').value=String(index);};
  const show=()=>{panel.hidden=false;button.classList.remove('secondary');button.setAttribute('aria-pressed','true');map.setLayoutProperty('weather-forecast','visibility','visible');};
  const hide=()=>{panel.hidden=true;button.classList.add('secondary');button.setAttribute('aria-pressed','false');if(map.getLayer('weather-forecast'))map.setLayoutProperty('weather-forecast','visibility','none');};
  button.addEventListener('click',async()=>{if(button.getAttribute('aria-pressed')==='true'){hide();return;}if(!forecast){button.textContent='CARREGANDO…';try{forecast=await api('/api/v1/radar/public/weather-forecast');const hour=new Date().getHours();index=Math.min(Math.max(forecast.times.findIndex(x=>Number(x.slice(11,13))>=hour),0),forecast.times.length-1);panel.innerHTML='<strong>PREVISÃO DE CHUVA · HOJE</strong><div><input type="range" aria-label="Horário da previsão" min="0" max="23" step="1"><output></output></div><p><i></i>leve <i></i>moderada <i></i>forte · ECMWF</p>';panel.querySelector('input').min=String(index);panel.querySelector('input').max=String(Math.max(0,forecast.times.length-1));panel.querySelector('input').addEventListener('input',event=>{index=Number(event.target.value);paint();});paint();}catch{button.textContent='PREVISÃO INDISPONÍVEL';return;}button.textContent='PREVISÃO DE CHUVA';}show();});
}
export function fitFront(map,tools,front){const bounds=new maplibregl.LngLatBounds();front.segments.forEach(s=>tools.slice(s.kmStart,s.kmEnd).forEach(c=>bounds.extend(c)));if(!bounds.isEmpty())map.fitBounds(bounds,{padding:window.innerWidth<700?55:110,maxZoom:14,duration:700});}
export function installPwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js?v=20260904-7',{scope:'/'}).catch(()=>{});}
